### ISSUE TITLE
Some Selections Invalid

### ISSUE THREAD

**Issue by mon5termatt** [LordZeuss/arr-installer#2]
![image](https://user-images.githubusercontent.com/43628254/192012866-7a4ecef0-f38e-40e3-b430-d954f7b9feed.png)

**Comment by mon5termatt** [comment]
![image](https://user-images.githubusercontent.com/43628254/192012866-7a4ecef0-f38e-40e3-b430-d954f7b9feed.png)

**Comment by LordZeuss** [comment]
That section is defining what the letters further in the script mean. If there is no option, it will output that and exit the script. I should add a note to that when trying to do it in portions of the script where there is no container properties to change, it wont allow you (like system update).

Ex: Clicking F to change properties will not work on the system update portion because there is nothing to change. When it asks if you want to install say sonarr, and you click F, then it will allow you to change it.

Hopefully that makes sense. Thanks for submitting this!

**Comment by mon5termatt** [comment]
ah thanks, that does make some more sense now.
